var Kinetic={};Kinetic.GlobalObject={stages:[],idCounter:0,tempNodes:[],animations:[],animIdCounter:0,animRunning:false,maxDragTimeInterval:20,frame:{time:0,timeDiff:0,lastTime:0},drag:{moving:false,node:undefined,offset:{x:0,y:0},lastDrawTime:0},extend:function(obj1,obj2){for(var key in obj2.prototype){if(obj2.prototype.hasOwnProperty(key)&&obj1.prototype[key]===undefined){obj1.prototype[key]=obj2.prototype[key];}}},addSetters:function(constructor,arr){for(var n=0;n<arr.length;n++){var attr=arr[n];this._addSetter(constructor,attr);}},addGetters:function(constructor,arr){for(var n=0;n<arr.length;n++){var attr=arr[n];this._addGetter(constructor,attr);}},_pullNodes:function(stage){var tempNodes=this.tempNodes;for(var n=0;n<tempNodes.length;n++){var node=tempNodes[n];if(node.getStage()!==undefined&&node.getStage()._id===stage._id){stage._addId(node);stage._addName(node);this.tempNodes.splice(n,1);n-=1;}}},_addAnimation:function(anim){anim.id=this.animIdCounter++;this.animations.push(anim);},_removeAnimation:function(anim){var id=anim.id;var animations=this.animations;for(var n=0;n<animations.length;n++){if(animations[n].id===id){this.animations.splice(n,1);return false;}}},_runFrames:function(){var nodes={};for(var n=0;n<this.animations.length;n++){var anim=this.animations[n];if(anim.node&&anim.node._id!==undefined){nodes[anim.node._id]=anim.node;}
anim.func(this.frame);}
for(var key in nodes){nodes[key].draw();}},_updateFrameObject:function(){var date=new Date();var time=date.getTime();if(this.frame.lastTime===0){this.frame.lastTime=time;}
else{this.frame.timeDiff=time-this.frame.lastTime;this.frame.lastTime=time;this.frame.time+=this.frame.timeDiff;}},_animationLoop:function(){if(this.animations.length>0){this._updateFrameObject();this._runFrames();var that=this;requestAnimFrame(function(){that._animationLoop();});}
else{this.animRunning=false;this.frame.lastTime=0;}},_handleAnimation:function(){var that=this;if(!this.animRunning){this.animRunning=true;that._animationLoop();}
else{this.frame.lastTime=0;}},_isElement:function(obj){return!!(obj&&obj.nodeType==1);},_isFunction:function(obj){return!!(obj&&obj.constructor&&obj.call&&obj.apply);},_isArray:function(obj){return obj.length!==undefined;},_isObject:function(obj){return(typeof obj=='object');},_isNumber:function(obj){return Object.prototype.toString.call(obj)=='[object Number]';},_hasMethods:function(obj){var names=[];for(var key in obj){if(this._isFunction(obj[key]))
names.push(key);}
return names.length>0;},_getXY:function(arg){if(this._isNumber(arg)){return{x:arg,y:arg};}
else if(this._isArray(arg)){if(arg.length===1){var val=arg[0]; //
if(this._isNumber(val)){return{x:val,y:val};}
else if(this._isArray(val)){return{x:val[0],y:val[1]};}
else if(this._isObject(val)){return val;}}
else if(arg.length>=2){return{x:arg[0],y:arg[1]};}}
else if(this._isObject(arg)){return arg;}
return{x:0,y:0};},_getSize:function(arg){if(this._isNumber(arg)){return{width:arg,height:arg};}
else if(this._isArray(arg)){if(arg.length===1){var val=arg[0];if(this._isNumber(val)){return{width:val, height:val};}
else if(this._isArray(val)){if(val.length>=4){return{width:val[2],height:val[3]};}
else if(val.length>=2){return{width:val[0],height:val[1]};}}
else if(this._isObject(val)){return val;}}
else if(arg.length>=4){return{width:arg[2],height:arg[3]};}
else if(arg.length>=2){return{width:arg[0],height:arg[1]};}}
else if(this._isObject(arg)){return arg;}
return{width:0,height:0};},_getPoints:function(arg){if(arg===undefined){return[];}
if(this._isObject(arg[0])){return arg;}
else{var arr=[];for(var n=0;n<arg.length;n+=2){arr.push({x:arg[n],y:arg[n+1]});}
return arr;}},_addSetter:function(constructor,attr){var that=this;var method='set'+attr.charAt(0).toUpperCase()+attr.slice(1);constructor.prototype[method]=function(arg){var obj={};obj[attr]=arg;this.setAttrs(obj);};},_addGetter:function(constructor,attr){var that=this;var method='get'+attr.charAt(0).toUpperCase()+attr.slice(1);constructor.prototype[method]=function(arg){return this.attrs[attr];};}};window.requestAnimFrame=(function(callback){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60);};})();Kinetic.Node=function(config){this.defaultNodeAttrs={visible:true,listen:true,name:undefined,alpha:1,x:0,y:0,scale:{x:1,y:1},rotation:0,offset:{x:0,y:0},dragConstraint:'none', dragBounds:{},draggable:false};this.setDefaultAttrs(this.defaultNodeAttrs);this.eventListeners={};this.setAttrs(config);this.on('draggableChange.kinetic_reserved',function(){if(this.attrs.draggable){this._listenDrag();}
else{this._dragCleanup();}});this.simulate('draggableChange');};Kinetic.Node.prototype={/**/
on:function(typesStr,handler){var types=typesStr.split(' ');for(var n=0;n<types.length;n++){var type=types[n];var event=type;var parts=event.split('.');var baseEvent=parts[0];var name=parts.length>1?parts[1]:'';if(!this.eventListeners[baseEvent]){this.eventListeners[baseEvent]=[];}
this.eventListeners[baseEvent].push({name:name,handler:handler});}},off:function(typesStr){var types=typesStr.split(' ');for(var n=0;n<types.length;n++){var type=types[n];var event=type;var parts=event.split('.');var baseEvent=parts[0];if(this.eventListeners[baseEvent]&&parts.length>1){var name=parts[1]; for(var i=0;i<this.eventListeners[baseEvent].length;i++){if(this.eventListeners[baseEvent][i].name===name){this.eventListeners[baseEvent].splice(i,1);if(this.eventListeners[baseEvent].length===0){delete this.eventListeners[baseEvent];break;}
i--;}}}
else{delete this.eventListeners[baseEvent];}}},getAttrs:function(){return this.attrs;},setDefaultAttrs:function(config){if(this.attrs===undefined){this.attrs={};}
if(config){for(var key in config){if(this.attrs[key]===undefined){this.attrs[key]=config[key];}}}},setAttrs:function(config){var go=Kinetic.GlobalObject;var that=this;if(config!==undefined){function setAttrs(obj,c,level){for(var key in c){var val=c[key];if(obj[key]===undefined){obj[key]={};}
/**/
if(go._isObject(val)&&!go._isArray(val)&&!go._isElement(val)&&!go._hasMethods(val)){if(!Kinetic.GlobalObject._isObject(obj[key])){obj[key]={};}
setAttrs(obj[key],val,level+1);}
else{switch(key){case 'rotationDeg':that._setAttr(obj,'rotation',c[key]*Math.PI/180);key='rotation';break;case 'offset':var pos=go._getXY(val);that._setAttr(obj[key],'x',pos.x);that._setAttr(obj[key],'y',pos.y);break;case 'scale':var pos=go._getXY(val);that._setAttr(obj[key],'x',pos.x); that._setAttr(obj[key],'y',pos.y);break;case 'points':that._setAttr(obj,key,go._getPoints(val));break;case 'crop':var pos=go._getXY(val);var size=go._getSize(val);that._setAttr(obj[key],'x',pos.x);that._setAttr(obj[key],'y',pos.y);that._setAttr(obj[key],'width',size.width);that._setAttr(obj[key],'height',size.height);break;default:that._setAttr(obj,key,c[key]);break;}
if(level===0){that._fireChangeEvent(key);}}}}
setAttrs(this.attrs,config,0);}},isVisible:function(){if(this.getParent()&&!this.getParent().isVisible()){return false;}
return this.attrs.visible;},show:function(){this.setAttrs({visible:true});},hide:function(){this.setAttrs({visible:false});},getZIndex:function(){return this.index;},
/**/
getAbsoluteZIndex:function(){var level=this.getLevel();var stage=this.getStage();var that=this;var index=0;function addChildren(children){var nodes=[];for(var n=0;n<children.length;n++){var child=children[n];index++;if(child.nodeType!=='Shape'){nodes=nodes.concat(child.getChildren());}
if(child._id===that._id){n=children.length;}}
if(nodes.length>0&&nodes[0].getLevel()<=level){addChildren(nodes);}}
if(that.nodeType!=='Stage'){addChildren(that.getStage().getChildren());}
return index;},getLevel:function(){var level=0;var parent=this.parent;while(parent){level++;parent=parent.parent;}
return level;},setScale:function(){this.setAttrs({scale:arguments});},setPosition:function(){var pos=Kinetic.GlobalObject._getXY(arguments);this.setAttrs(pos);},getPosition:function(){return{x:this.attrs.x,y:this.attrs.y};},getAbsolutePosition:function(){return this.getAbsoluteTransform().getTranslation();},setAbsolutePosition:function(){var pos=Kinetic.GlobalObject._getXY(arguments);var rot=this.attrs.rotation;var scale={x:this.attrs.scale.x,y:this.attrs.scale.y};var offset={x:this.attrs.offset.x,y:this.attrs.offset.y};this.attrs.rotation=0;this.attrs.scale={x:1,y:1};var it=this.getAbsoluteTransform();it.invert();it.translate(pos.x,pos.y);pos={x:this.attrs.x+it.getTranslation().x,y:this.attrs.y+it.getTranslation().y};this.setPosition(pos.x,pos.y);this.rotate(rot);this.attrs.scale={x:scale.x,y:scale.y};},move:function(){var pos=Kinetic.GlobalObject._getXY(arguments);var x=this.getX();var y=this.getY();if(pos.x!==undefined){x+=pos.x;}
if(pos.y!==undefined){y+=pos.y;}
this.setAttrs({x:x,y:y});},setRotationDeg:function(deg){this.setRotation(deg*Math.PI/180);},getRotationDeg:function(){return this.attrs.rotation*180/Math.PI;},rotate:function(theta){this.setAttrs({rotation:this.getRotation()+theta});},rotateDeg:function(deg){this.setAttrs({rotation:this.getRotation()+(deg*Math.PI/180)});},listen:function(listen){this.setAttrs({listen:listen});},isListening:function(){return this.attrs.listen;},moveToTop:function(){var index=this.index;this.parent.children.splice(index,1);this.parent.children.push(this);this.parent._setChildrenIndices();},moveUp:function(){var index=this.index;this.parent.children.splice(index,1);this.parent.children.splice(index+1,0,this);this.parent._setChildrenIndices();},moveDown:function(){var index=this.index;if(index>0){this.parent.children.splice(index,1);this.parent.children.splice(index-1,0,this);this.parent._setChildrenIndices();}},moveToBottom:function(){var index=this.index;this.parent.children.splice(index,1);this.parent.children.unshift(this);this.parent._setChildrenIndices();},/**/
setZIndex:function(zIndex){var index=this.index;this.parent.children.splice(index,1);this.parent.children.splice(zIndex,0,this);this.parent._setChildrenIndices();},getAbsoluteAlpha:function(){var absAlpha=1;var node=this;while(node.nodeType!=='Stage'){absAlpha*=node.attrs.alpha;node=node.parent;}
return absAlpha;},draggable:function(draggable){this.setAttrs({draggable:draggable});},isDragging:function(){var go=Kinetic.GlobalObject;return go.drag.node!==undefined&&go.drag.node._id===this._id&&go.drag.moving;},moveTo:function(newContainer){var parent=this.parent;parent.children.splice(this.index,1);parent._setChildrenIndices();newContainer.children.push(this);this.index=newContainer.children.length-1;this.parent=newContainer;newContainer._setChildrenIndices();},getParent:function(){return this.parent;},getLayer:function(){if(this.nodeType==='Layer'){return this;}
else{return this.getParent().getLayer();}},getStage:function(){if(this.nodeType==='Stage'){return this;}
else{
if(this.getParent()===undefined){return undefined;}
else{return this.getParent().getStage();}}},simulate:function(eventType){this._handleEvent(eventType,{});},setOffset:function(){this.setAttrs({offset:arguments});},/**/
transitionTo:function(config){var go=Kinetic.GlobalObject;if(this.transAnim!==undefined){go._removeAnimation(this.transAnim);this.transAnim=undefined;}
var node=this.nodeType==='Stage'?this:this.getLayer();var that=this;var trans=new Kinetic.Transition(this,config);var anim={func:function(){trans._onEnterFrame();},node:node};this.transAnim=anim;go._addAnimation(anim);trans.onFinished=function(){go._removeAnimation(anim);that.transAnim=undefined;if(config.callback!==undefined){config.callback();}
anim.node.draw();};trans.start();go._handleAnimation();return trans;},/**/
getAbsoluteTransform:function(){var am=new Kinetic.Transform();var family=[];var parent=this.parent;family.unshift(this);while(parent){family.unshift(parent);parent=parent.parent;}
for(var n=0;n<family.length;n++){var node=family[n];var m=node.getTransform();am.multiply(m);}
return am;},getTransform:function(){var m=new Kinetic.Transform();if(this.attrs.x!==0||this.attrs.y!==0){m.translate(this.attrs.x,this.attrs.y);}
if(this.attrs.rotation!==0){m.rotate(this.attrs.rotation);}
if(this.attrs.scale.x!==1||this.attrs.scale.y!==1){m.scale(this.attrs.scale.x,this.attrs.scale.y);}
return m;},_fireChangeEvent:function(attr){this._handleEvent(attr+'Change',{});},_setAttr:function(obj,attr,val){if(val!==undefined){obj[attr]=val;}},_listenDrag:function(){this._dragCleanup();var go=Kinetic.GlobalObject;var that=this;this.on('mousedown.initdrag touchstart.initdrag',function(evt){that._initDrag();});},_initDrag:function(){var go=Kinetic.GlobalObject;var stage=this.getStage();var pos=stage.getUserPosition();if(pos){var m=this.getTransform().getTranslation();var am=this.getAbsoluteTransform().getTranslation();go.drag.node=this;go.drag.offset.x=pos.x-this.getAbsoluteTransform().getTranslation().x;go.drag.offset.y= pos.y-this.getAbsoluteTransform().getTranslation().y;}},_dragCleanup:function(){this.off('mousedown.initdrag');this.off('touchstart.initdrag');},_handleEvent:function(eventType,evt){if(this.nodeType==='Shape'){evt.shape=this;}
var stage=this.getStage();var mouseoverNode=stage?stage.mouseoverShape:null;var mouseoutNode=stage?stage.mouseoutShape:null;var el=this.eventListeners;var okayToRun=true;if(eventType==='mouseover'&&mouseoutNode&&mouseoutNode._id===this._id){okayToRun=false;}
else if(eventType==='mouseout'&&mouseoverNode&&mouseoverNode._id===this._id){okayToRun=false;}
if(el[eventType]&&okayToRun){var events=el[eventType];for(var i=0;i<events.length;i++){events[i].handler.apply(this,[evt]);}}
var mouseoverParent=mouseoverNode?mouseoverNode.parent:undefined;var mouseoutParent=mouseoutNode?mouseoutNode.parent:undefined;if(!evt.cancelBubble&&this.parent&&this.parent.nodeType!=='Stage'){this._handleEvent.call(this.parent,eventType,evt);}}};Kinetic.GlobalObject.addSetters(Kinetic.Node,['x','y','detectionType','rotation','alpha','name','id','dragConstraint','dragBounds']);Kinetic.GlobalObject.addGetters(Kinetic.Node,['scale','x','y','detectionType','rotation','alpha','name','id','offset','dragConstraint','dragBounds']);
/**/
/**/
Kinetic.Container=function(){this.children=[];};Kinetic.Container.prototype={getChildren:function(){return this.children;},removeChildren:function(){while(this.children.length>0){this.remove(this.children[0]);}},/**/
add:function(child){child._id=Kinetic.GlobalObject.idCounter++;child.index=this.children.length;child.parent=this;this.children.push(child);var stage=child.getStage();if(stage===undefined){var go=Kinetic.GlobalObject;go.tempNodes.push(child);}
else{stage._addId(child);stage._addName(child);var go=Kinetic.GlobalObject;go._pullNodes(stage);}
if(this._add!==undefined){this._add(child);}
return this;},remove:function(child){if(child&&child.index!==undefined&&this.children[child.index]._id==child._id){var stage=this.getStage();if(stage!==undefined){stage._removeId(child);stage._removeName(child);}
var go=Kinetic.GlobalObject;for(var n=0;n<go.tempNodes.length;n++){var node=go.tempNodes[n];if(node._id===child._id){go.tempNodes.splice(n,1);break;}}
this.children.splice(child.index,1);this._setChildrenIndices();if(child.children){for(var n=0;n<child.children.length;n++){child.remove(child.children[n]);}}
if(this._remove!==undefined){this._remove(child);}}
return this;},/**/
get:function(selector){var stage=this.getStage();var arr;var key=selector.slice(1);if(selector.charAt(0)==='#'){arr=stage.ids[key]!==undefined?[stage.ids[key]]:[];}
else if(selector.charAt(0)==='.'){arr=stage.names[key]!==undefined?stage.names[key]:[];}
else if(selector==='Shape'||selector==='Group'||selector==='Layer'){return this._getNodes(selector);}
else{return false;}
var retArr=[];for(var n=0;n<arr.length;n++){var node=arr[n];if(this.isAncestorOf(node)){retArr.push(node);}}
return retArr;},isAncestorOf:function(node){if(this.nodeType==='Stage'){return true;}
var parent=node.getParent();while(parent){if(parent._id===this._id){return true;}
parent=parent.getParent();}
return false;},_getNodes:function(sel){var arr=[];function traverse(cont){var children=cont.getChildren();for(var n=0;n<children.length;n++){var child=children[n];if(child.nodeType===sel){arr.push(child);}
else if(child.nodeType!=='Shape'){traverse(child);}}}
 traverse(this);return arr;},_drawChildren:function(){var stage=this.getStage();var children=this.children;for(var n=0;n<children.length;n++){var child=children[n];if(child.nodeType==='Shape'){if(child.isVisible()&&stage.isVisible()){child._draw(child.getLayer());}}
else{child.draw();}}},_setChildrenIndices:function(){/**/
if(this.nodeType==='Stage'){var canvases=this.content.children;var bufferCanvas=canvases[0];var backstageCanvas=canvases[1];this.content.innerHTML='';this.content.appendChild(bufferCanvas);this.content.appendChild(backstageCanvas);}
for(var n=0;n<this.children.length;n++){this.children[n].index=n;if(this.nodeType==='Stage'){this.content.appendChild(this.children[n].canvas);}}}};Kinetic.Stage=function(config){this.setDefaultAttrs({width:400,height:200,throttle:80});if(typeof config.container==='string'){config.container=document.getElementById(config.container);}
Kinetic.Container.apply(this,[]);Kinetic.Node.apply(this,[config]);this._setStageDefaultProperties();this._id=Kinetic.GlobalObject.idCounter++;this._buildDOM();this._bindContentEvents();this._prepareDrag();this.on('widthChange.kinetic_reserved',function(){this._resizeDOM();});this.on('heightChange.kinetic_reserved',function(){this._resizeDOM();});var go=Kinetic.GlobalObject;go.stages.push(this);this._addId(this);this._addName(this);};Kinetic.Stage.prototype={onFrame:function(func){var go=Kinetic.GlobalObject;this.anim={func:func};},start:function(){if(!this.animRunning){var go=Kinetic.GlobalObject;go._addAnimation(this.anim);go._handleAnimation();this.animRunning=true;}},stop:function(){var go=Kinetic.GlobalObject;go._removeAnimation(this.anim);this.animRunning=false;},draw:function(){this._drawChildren();},setSize:function(){var size=Kinetic.GlobalObject._getSize(arguments);this.setAttrs(size);},getSize:function(){return{width:this.attrs.width,height:this.attrs.height};},clear:function(){var layers=this.children;for(var n=0;n<layers.length;n++){layers[n].clear();}},/**/
toDataURL:function(callback,mimeType,quality){var bufferLayer=this.bufferLayer;var bufferContext=bufferLayer.getContext();var layers=this.children;var that=this;function addLayer(n){var dataURL=layers[n].getCanvas().toDataURL();var imageObj=new Image();imageObj.onload=function(){bufferContext.drawImage(this,0,0);n++;if(n<layers.length){addLayer(n);}
else{try{callback(bufferLayer.getCanvas().toDataURL(mimeType,quality));}
catch(exception){callback(bufferLayer.getCanvas().toDataURL());}}};imageObj.src=dataURL;}
bufferLayer.clear();addLayer(0);},toJSON:function(){var go=Kinetic.GlobalObject;function addNode(node){var obj={};var cleanAttrs=node.attrs;for(var key in cleanAttrs){var val=cleanAttrs[key];if(go._isFunction(val)||go._isElement(val)||go._hasMethods(val)){cleanAttrs[key]=undefined;}}
 obj.attrs=cleanAttrs;obj.nodeType=node.nodeType;obj.shapeType=node.shapeType;if(node.nodeType!=='Shape'){obj.children=[];var children=node.getChildren();for(var n=0;n<children.length;n++){var child=children[n];obj.children.push(addNode(child));}}
return obj;}
return JSON.stringify(addNode(this));},reset:function(){this.removeChildren();this._setStageDefaultProperties();this.setAttrs(this.defaultNodeAttrs);},load:function(json){this.reset();function loadNode(node,obj){var children=obj.children;if(children!==undefined){for(var n=0;n<children.length;n++){var child=children[n];var type;if(child.nodeType==='Shape'){if(child.shapeType===undefined){type='Shape';}
else{type=child.shapeType;}}
else{ type=child.nodeType;}
var no=new Kinetic[type](child.attrs);node.add(no);loadNode(no,child);}}}
var obj=JSON.parse(json);this.attrs=obj.attrs;loadNode(this,obj);this.draw();},getMousePosition:function(evt){return this.mousePos;},getTouchPosition:function(evt){return this.touchPos;},/**/
getUserPosition:function(evt){return this.getTouchPosition()||this.getMousePosition();},getContainer:function(){return this.attrs.container;},getContent:function(){return this.content;},getStage:function(){return this;},getIntersections:function(){var pos=Kinetic.GlobalObject._getXY(arguments);var arr=[];var shapes=this.get('Shape');for(var n=0;n<shapes.length;n++){var shape=shapes[n];if(shape.intersects(pos)){arr.push(shape);}}
return arr;},getDOM:function(){return this.content;},_resizeDOM:function(){var width=this.attrs.width;var height=this.attrs.height;this.content.style.width=width+'px';this.content.style.height=height+'px';this.bufferLayer.getCanvas().width=width;this.bufferLayer.getCanvas().height=height;this.pathLayer.getCanvas().width=width;this.pathLayer.getCanvas().height=height;var layers=this.children;for(var n=0;n<layers.length;n++){var layer=layers[n];layer.getCanvas().width=width;layer.getCanvas().height=height;layer.draw();}},_remove:function(layer){
/**/
try{this.content.removeChild(layer.canvas);}
catch(e){}},_add:function(layer){layer.canvas.width=this.attrs.width;layer.canvas.height=this.attrs.height;layer.draw();this.content.appendChild(layer.canvas);layer.lastDrawTime=0;},_detectEvent:function(shape,evt){var isDragging=Kinetic.GlobalObject.drag.moving;var go=Kinetic.GlobalObject;var pos=this.getUserPosition();var el=shape.eventListeners;if(this.targetShape&&shape._id===this.targetShape._id){this.targetFound=true;}
if(shape.isVisible()&&pos!==undefined&&shape.intersects(pos)){if(!isDragging&&this.mouseDown){this.mouseDown=false;this.clickStart=true;shape._handleEvent('mousedown',evt);return true;}
else if(this.mouseUp){this.mouseUp=false;shape._handleEvent('mouseup',evt);if(this.clickStart){if((!go.drag.moving)||!go.drag.node){shape._handleEvent('click',evt);if(shape.inDoubleClickWindow){shape._handleEvent('dblclick',evt);}
shape.inDoubleClickWindow=true;setTimeout(function(){shape.inDoubleClickWindow=false;},this.dblClickWindow);}}
return true;}
if(!isDragging&&this.touchStart&&!this.touchMove){this.touchStart=false;this.tapStart=true;shape._handleEvent('touchstart',evt);return true;}
else if(this.touchEnd){this.touchEnd=false;shape._handleEvent('touchend',evt);if(this.tapStart){if((!go.drag.moving)||!go.drag.node){shape._handleEvent('tap',evt);if(shape.inDoubleClickWindow){shape._handleEvent('dbltap',evt);}
shape.inDoubleClickWindow=true;setTimeout(function(){shape.inDoubleClickWindow=false;},this.dblClickWindow);}}
return true;}
else if(!isDragging&&this._isNewTarget(shape,evt)){/**/
if(this.mouseoutShape){this.mouseoverShape=shape;this.mouseoutShape._handleEvent('mouseout',evt);this.mouseoverShape=undefined;}
shape._handleEvent('mouseover',evt);this._setTarget(shape);return true;}
else if(!isDragging&&this.mouseMove){shape._handleEvent('mousemove',evt);return true;}
else if(!isDragging&&this.touchMove){shape._handleEvent('touchmove',evt);return true;}}
else if(!isDragging&&this.targetShape&&this.targetShape._id===shape._id){this._setTarget(undefined);this.mouseoutShape=shape;return true;}
return false;},_setTarget:function(shape){this.targetShape=shape;this.targetFound=true;},_isNewTarget:function(shape,evt){if(!this.targetShape||(!this.targetFound&&shape._id!==this.targetShape._id)){if(this.targetShape){var oldEl=this.targetShape.eventListeners;if(oldEl){this.mouseoutShape=this.targetShape;}}
return true;}
else{return false;}},_traverseChildren:function(obj,evt){var children=obj.children;for(var i=children.length-1;i>=0;i--){var child=children[i];if(child.attrs.listen){if(child.nodeType==='Shape'){var exit=this._detectEvent(child,evt);if(exit){return true;}}
else{var exit=this._traverseChildren(child,evt);if(exit){return true;}}}}
return false;},_handleStageEvent:function(evt){var date=new Date();var time=date.getTime();this.lastEventTime=time;var go=Kinetic.GlobalObject;if(!evt){evt=window.event;}
this._setMousePosition(evt);this._setTouchPosition(evt);this.pathLayer.clear();this.targetFound=false;var shapeDetected=false;for(var n=this.children.length-1;n>=0;n--){var layer=this.children[n];if(layer.isVisible()&&n>=0&&layer.attrs.listen){if(this._traverseChildren(layer,evt)){shapeDetected=true;break;}}}
if(!shapeDetected&&this.mouseoutShape){this.mouseoutShape._handleEvent('mouseout',evt);this.mouseoutShape=undefined;}},_bindContentEvents:function(){var go=Kinetic.GlobalObject;var that=this;this.content.addEventListener('mousedown',function(evt){that.mouseDown=true;that.mouseUp=false;that.mouseMove=false;that._handleStageEvent(evt);if(that.attrs.draggable){that._initDrag();}},false);this.content.addEventListener('mousemove',function(evt){var throttle=that.attrs.throttle;var date=new Date();var time=date.getTime();var timeDiff=time-that.lastEventTime;var tt=1000/throttle;if(timeDiff>=tt){that.mouseDown=false;that.mouseUp=false;that._handleStageEvent(evt);}},false);this.content.addEventListener('mouseup',function(evt){that.mouseDown=false;that.mouseUp=true;that.mouseMove=false;that._handleStageEvent(evt);that.clickStart=false;},false);this.content.addEventListener('mouseover',function(evt){that._handleStageEvent(evt);},false);this.content.addEventListener('mouseout',function(evt){var targetShape=that.targetShape;if(targetShape){targetShape._handleEvent('mouseout',evt);that.targetShape=undefined;}
that.mousePos=undefined;},false);this.content.addEventListener('touchstart',function(evt){evt.preventDefault();that.touchStart=true;that.touchEnd=false;that.touchMove=false;that._handleStageEvent(evt);if(that.attrs.draggable){that._initDrag();}},false);this.content.addEventListener('touchmove',function(evt){var throttle=that.attrs.throttle;var date=new Date();var time=date.getTime();var timeDiff=time-that.lastEventTime;var tt=1000/throttle;if(timeDiff>=tt){/**/
setTimeout(function(){evt.preventDefault();that.touchEnd=false;that.touchMove=true;that._handleStageEvent(evt);},5);}},false);this.content.addEventListener('touchend',function(evt){that.touchStart=false;that.touchEnd=true;that.touchMove=false;that._handleStageEvent(evt);that.tapStart=false;},false);},_setMousePosition:function(evt){var mouseX=evt.offsetX||(evt.clientX-this._getContentPosition().left+window.pageXOffset);var mouseY=evt.offsetY||(evt.clientY-this._getContentPosition().top+window.pageYOffset);this.mousePos={x:mouseX,y:mouseY};},_setTouchPosition:function(evt){if(evt.touches!==undefined&&evt.touches.length===1){var touch=evt.touches[0];var touchX=touch.clientX-this._getContentPosition().left+window.pageXOffset;var touchY=touch.clientY-this._getContentPosition().top+window.pageYOffset;this.touchPos={x:touchX,y:touchY};}},_getContentPosition:function(){var obj=this.content;var top=0;var left=0;while(obj&&obj.tagName!=='BODY'){top+=obj.offsetTop-obj.scrollTop;left+=obj.offsetLeft-obj.scrollLeft;obj=obj.offsetParent;}
return{top:top,left:left};},
_modifyPathContext:function(context){context.stroke=function(){};context.fill=function(){};context.fillRect=function(x,y,width,height){context.rect(x,y,width,height);};context.strokeRect=function(x,y,width,height){context.rect(x,y,width,height);};context.drawImage=function(){};context.fillText=function(){};context.strokeText=function(){};},_endDrag:function(evt){var go=Kinetic.GlobalObject;if(go.drag.node){if(go.drag.moving){go.drag.moving=false;go.drag.node._handleEvent('dragend',evt);}}
go.drag.node=undefined;},_prepareDrag:function(){var that=this;this._onContent('mousemove touchmove',function(evt){var go=Kinetic.GlobalObject;var node=go.drag.node;if(node){var pos=that.getUserPosition();var dc=node.attrs.dragConstraint;var db=node.attrs.dragBounds;var lastNodePos={x:node.attrs.x,y:node.attrs.y};var newNodePos={x:pos.x-go.drag.offset.x,y:pos.y-go.drag.offset.y};if(db.left!==undefined&&newNodePos.x<db.left){newNodePos.x=db.left;}
if(db.right!==undefined&&newNodePos.x>db.right){newNodePos.x=db.right;}
if(db.top!==undefined&&newNodePos.y<db.top){ newNodePos.y=db.top;}
if(db.bottom!==undefined&&newNodePos.y>db.bottom){newNodePos.y=db.bottom;}
node.setAbsolutePosition(newNodePos);if(dc==='horizontal'){node.attrs.y=lastNodePos.y;}
else if(dc==='vertical'){node.attrs.x=lastNodePos.x;}
if(go.drag.node.nodeType==='Stage'){go.drag.node.draw();}
else{go.drag.node.getLayer().draw();}
if(!go.drag.moving){go.drag.moving=true;go.drag.node._handleEvent('dragstart',evt);}
go.drag.node._handleEvent('dragmove',evt);}},false);this._onContent('mouseup touchend mouseout',function(evt){that._endDrag(evt);});},_buildDOM:function(){this.content=document.createElement('div');this.content.style.position='relative';this.content.style.display='inline-block';this.content.className='kineticjs-content';this.attrs.container.appendChild(this.content);this.bufferLayer=new Kinetic.Layer({name:'bufferLayer'});this.pathLayer=new Kinetic.Layer({name:'pathLayer'});this.bufferLayer.parent=this;this.pathLayer.parent=this;this._modifyPathContext(this.pathLayer.context);this.bufferLayer.getCanvas().style.display='none';this.pathLayer.getCanvas().style.display='none';this.bufferLayer.canvas.className='kineticjs-buffer-layer';this.content.appendChild(this.bufferLayer.canvas);this.pathLayer.canvas.className='kineticjs-path-layer';this.content.appendChild(this.pathLayer.canvas);this.setSize(this.attrs.width,this.attrs.height);this._resizeDOM();},_addId:function(node){if(node.attrs.id!==undefined){this.ids[node.attrs.id]=node;}},_removeId:function(node){if(node.attrs.id!==undefined){this.ids[node.attrs.id]=undefined;}},_addName:function(node){var name=node.attrs.name;if(name!==undefined){if(this.names[name]===undefined){this.names[name]=[];}
this.names[name].push(node);}},_removeName:function(node){if(node.attrs.name!==undefined){var nodes=this.names[node.attrs.name];if(nodes!==undefined){for(var n=0;n<nodes.length;n++){var no=nodes[n];if(no._id===node._id){nodes.splice(n,1);}}
if(nodes.length===0){delete this.names[node.attrs.name];}}}},_onContent:function(typesStr,handler){var types=typesStr.split(' ');for(var n=0;n<types.length;n++){var baseEvent=types[n];this.content.addEventListener(baseEvent,handler,false);}},_setStageDefaultProperties:function(){this.nodeType='Stage';this.lastEventTime=0;this.dblClickWindow=400;this.targetShape=undefined;this.targetFound=false;this.mouseoverShape=undefined;this.mouseoutShape=undefined;this.mousePos=undefined;this.mouseDown=false;this.mouseUp=false;this.mouseMove=false;this.clickStart=false;this.touchPos=undefined;this.touchStart=false;this.touchEnd=false;this.touchMove=false;this.tapStart=false;this.ids={};this.names={};this.anim=undefined;this.animRunning=false;}};Kinetic.GlobalObject.extend(Kinetic.Stage,Kinetic.Container);Kinetic.GlobalObject.extend(Kinetic.Stage,Kinetic.Node);Kinetic.GlobalObject.addSetters(Kinetic.Stage,['width','height','throttle']);Kinetic.GlobalObject.addGetters(Kinetic.Stage,['width','height','throttle']);Kinetic.Layer=function(config){this.setDefaultAttrs({throttle:80});this.nodeType='Layer';this.lastDrawTime=0;this.beforeDrawFunc=undefined;this.afterDrawFunc=undefined;this.canvas=document.createElement('canvas');this.context=this.canvas.getContext('2d');this.canvas.style.position='absolute';Kinetic.Container.apply(this,[]);Kinetic.Node.apply(this,[config]);};Kinetic.Layer.prototype={draw:function(){var throttle=this.attrs.throttle;var date=new Date();var time=date.getTime();var timeDiff=time-this.lastDrawTime;var tt=1000/throttle;if(timeDiff>=tt){this._draw();if(this.drawTimeout!==undefined){clearTimeout(this.drawTimeout);this.drawTimeout=undefined;}}
 else if(this.drawTimeout===undefined){var that=this;this.drawTimeout=setTimeout(function(){that.draw();},17);}},setThrottle:function(throttle){this.attrs.throttle=throttle;},getThrottle:function(){return this.attrs.throttle;},beforeDraw:function(func){this.beforeDrawFunc=func;},afterDraw:function(func){this.afterDrawFunc=func;},clear:function(){var context=this.getContext();var canvas=this.getCanvas();context.clearRect(0,0,canvas.width,canvas.height);},getCanvas:function(){return this.canvas;},getContext:function(){return this.context;},_draw:function(){var date=new Date();var time=date.getTime();this.lastDrawTime=time;if(this.beforeDrawFunc!==undefined){this.beforeDrawFunc.call(this);}
this.clear();if(this.isVisible()){if(this.attrs.drawFunc!==undefined){this.attrs.drawFunc.call(this);}
this._drawChildren();}
if(this.afterDrawFunc!==undefined){this.afterDrawFunc.call(this);}}};Kinetic.GlobalObject.extend(Kinetic.Layer,Kinetic.Container);Kinetic.GlobalObject.extend(Kinetic.Layer,Kinetic.Node);Kinetic.Group=function(config){this.nodeType='Group';;Kinetic.Container.apply(this,[]);Kinetic.Node.apply(this,[config]);};Kinetic.Group.prototype={draw:function(){if(this.attrs.visible){this._drawChildren();}}};Kinetic.GlobalObject.extend(Kinetic.Group,Kinetic.Container);Kinetic.GlobalObject.extend(Kinetic.Group,Kinetic.Node);Kinetic.Shape=function(config){this.setDefaultAttrs({fill:undefined,stroke:undefined,strokeWidth:undefined,lineJoin:undefined,detectionType:'path',shadow:{blur:10,alpha:1,offset:{x:0,y:0}}});this.data=[];this.nodeType='Shape';this.appliedShadow=false;Kinetic.Node.apply(this,[config]);};Kinetic.Shape.prototype={getContext:function(){if(this.tempLayer===undefined){return null;}
else{return this.tempLayer.getContext();}},getCanvas:function(){return this.tempLayer.getCanvas();},stroke:function(){var appliedShadow=false;var context=this.getContext();context.save();if(!!this.attrs.stroke||!!this.attrs.strokeWidth){if(!this.appliedShadow){appliedShadow=this._applyShadow();}
var stroke=!!this.attrs.stroke?this.attrs.stroke:'black';var strokeWidth=!!this.attrs.strokeWidth?this.attrs.strokeWidth:2;context.lineWidth=strokeWidth;context.strokeStyle=stroke;context.stroke();}
context.restore();if(appliedShadow){this.stroke();}},/**/
fill:function(){var appliedShadow=false;var context=this.getContext();context.save();var fill=this.attrs.fill;if(!!fill){if(!this.appliedShadow){appliedShadow=this._applyShadow();}
var s=fill.start;var e=fill.end;var f=null;if(typeof fill=='string'){f=this.attrs.fill;context.fillStyle=f;context.fill();}
else if(fill.image!==undefined){var repeat=fill.repeat===undefined?'repeat':fill.repeat;f=context.createPattern(fill.image,repeat);context.save();if(fill.offset!==undefined){context.translate(fill.offset.x,fill.offset.y);}
context.fillStyle=f;context.fill();context.restore();}
else if(s.radius===undefined&&e.radius===undefined){var context=this.getContext();var grd=context.createLinearGradient(s.x,s.y,e.x,e.y);var colorStops=fill.colorStops;for(var n=0;n<colorStops.length;n+=2){grd.addColorStop(colorStops[n],colorStops[n+1]);}
f=grd;context.fillStyle=f;context.fill();}
else if(s.radius!==undefined&&e.radius!==undefined){var context=this.getContext();var grd=context.createRadialGradient(s.x,s.y,s.radius,e.x,e.y,e.radius);var colorStops=fill.colorStops;for(var n=0;n<colorStops.length;n+=2){grd.addColorStop(colorStops[n],colorStops[n+1]);}
f=grd;context.fillStyle=f;context.fill();}
else{f='black';context.fillStyle=f;context.fill();}}
context.restore();if(appliedShadow){this.fill();}},fillText:function(text,x,y){var appliedShadow=false;var context=this.getContext();context.save(); if(this.attrs.textFill!==undefined){if(!this.appliedShadow){appliedShadow=this._applyShadow();}
context.fillStyle=this.attrs.textFill;context.fillText(text,x,y);}
context.restore();if(appliedShadow){this.fillText(text,x,y);}},strokeText:function(text,x,y){var appliedShadow=false;var context=this.getContext();context.save();if(this.attrs.textStroke!==undefined||this.attrs.textStrokeWidth!==undefined){if(!this.appliedShadow){appliedShadow=this._applyShadow();}
if(this.attrs.textStroke===undefined){this.attrs.textStroke='black';}
else if(this.attrs.textStrokeWidth===undefined){this.attrs.textStrokeWidth=2;}
context.lineWidth=this.attrs.textStrokeWidth;context.strokeStyle=this.attrs.textStroke;context.strokeText(text,x,y);}
context.restore();if(appliedShadow){this.strokeText(text,x,y);}},drawImage:function(){var appliedShadow=false;var context=this.getContext();context.save();var a=arguments;if(a.length===5||a.length===9){if(!this.appliedShadow){appliedShadow=this._applyShadow();}
switch(a.length){case 5:context.drawImage(a[0],a[1],a[2],a[3],a[4]);break;case 9:context.drawImage(a[0],a[1],a[2],a[3],a[4],a[5],a[6],a[7],a[8]); break;}}
context.restore();if(appliedShadow){this.drawImage.apply(this,arguments);}},applyLineJoin:function(){var context=this.getContext();if(this.attrs.lineJoin!==undefined){context.lineJoin=this.attrs.lineJoin;}},_applyShadow:function(){var context=this.getContext();var s=this.attrs.shadow;if(s!==undefined){var aa=this.getAbsoluteAlpha();var sa=this.attrs.shadow.alpha;if(sa!==undefined&&s.color!==undefined){context.globalAlpha=sa*aa;context.shadowColor=s.color;context.shadowBlur=s.blur;context.shadowOffsetX=s.offset.x;context.shadowOffsetY=s.offset.y;this.appliedShadow=true;return true;}}
return false;},saveData:function(){var stage=this.getStage();var w=stage.attrs.width;var h=stage.attrs.height;var bufferLayer=stage.bufferLayer;var bufferLayerContext=bufferLayer.getContext();bufferLayer.clear();this._draw(bufferLayer);var imageData=bufferLayerContext.getImageData(0,0,w,h);this.data=imageData.data;},clearData:function(){this.data=[];},intersects:function(){var pos=Kinetic.GlobalObject._getXY(arguments);var stage=this.getStage();if(this.attrs.detectionType==='path'){ var pathLayer=stage.pathLayer;var pathLayerContext=pathLayer.getContext();this._draw(pathLayer);return pathLayerContext.isPointInPath(pos.x,pos.y);}
else{var w=stage.attrs.width;var alpha=this.data[((w*pos.y)+pos.x)*4+3];return(alpha!==undefined&&alpha!==0);}},_draw:function(layer){if(layer!==undefined&&this.attrs.drawFunc!==undefined){var stage=layer.getStage();var context=layer.getContext();var family=[];var parent=this.parent;family.unshift(this);while(parent){family.unshift(parent);parent=parent.parent;}
context.save();for(var n=0;n<family.length;n++){var node=family[n];var t=node.getTransform();if(node.attrs.offset.x!==0||node.attrs.offset.y!==0){t.translate(-1*node.attrs.offset.x,-1*node.attrs.offset.y);}
var m=t.getMatrix();context.transform(m[0],m[1],m[2],m[3],m[4],m[5]);}
this.tempLayer=layer;if(this.getAbsoluteAlpha()!==1){context.globalAlpha=this.getAbsoluteAlpha();}
this.applyLineJoin();this.appliedShadow=false;this.attrs.drawFunc.call(this);context.restore();}}};Kinetic.GlobalObject.extend(Kinetic.Shape,Kinetic.Node);Kinetic.GlobalObject.addSetters(Kinetic.Shape,['fill','stroke','lineJoin','strokeWidth','shadow','drawFunc']);Kinetic.GlobalObject.addGetters(Kinetic.Shape,['fill','stroke','lineJoin','strokeWidth','shadow','drawFunc']);Kinetic.Rect=function(config){this.setDefaultAttrs({width:0,height:0,cornerRadius:0});this.shapeType="Rect";config.drawFunc=function(){var context=this.getContext();context.beginPath();if(this.attrs.cornerRadius===0){//
context.rect(0,0,this.attrs.width,this.attrs.height);}
else{context.moveTo(this.attrs.cornerRadius,0);context.lineTo(this.attrs.width-this.attrs.cornerRadius,0);context.arc(this.attrs.width-this.attrs.cornerRadius,this.attrs.cornerRadius,this.attrs.cornerRadius,Math.PI*3/2,0,false);context.lineTo(this.attrs.width,this.attrs.height-this.attrs.cornerRadius);context.arc(this.attrs.width-this.attrs.cornerRadius,this.attrs.height-this.attrs.cornerRadius,this.attrs.cornerRadius,0,Math.PI/2,false);context.lineTo(this.attrs.cornerRadius,this.attrs.height);context.arc(this.attrs.cornerRadius,this.attrs.height-this.attrs.cornerRadius,this.attrs.cornerRadius,Math.PI/2,Math.PI,false);context.lineTo(0,this.attrs.cornerRadius);context.arc(this.attrs.cornerRadius,this.attrs.cornerRadius,this.attrs.cornerRadius,Math.PI,Math.PI*3/2,false);}
context.closePath();this.fill();this.stroke();};Kinetic.Shape.apply(this,[config]);};Kinetic.Rect.prototype={setSize:function(){var size=Kinetic.GlobalObject._getSize(arguments);this.setAttrs(size);},getSize:function(){return{width:this.attrs.width,height:this.attrs.height};}};Kinetic.GlobalObject.extend(Kinetic.Rect,Kinetic.Shape);Kinetic.GlobalObject.addSetters(Kinetic.Rect,['width','height','cornerRadius']);Kinetic.GlobalObject.addGetters(Kinetic.Rect,['width','height','cornerRadius']);Kinetic.Circle=function(config){this.setDefaultAttrs({radius:0});this.shapeType="Circle";config.drawFunc=function(){var canvas=this.getCanvas();var context=this.getContext();context.beginPath();context.arc(0,0,this.attrs.radius,0,Math.PI*2,true);context.closePath();this.fill();this.stroke();};Kinetic.Shape.apply(this,[config]);};Kinetic.GlobalObject.extend(Kinetic.Circle,Kinetic.Shape);Kinetic.GlobalObject.addSetters(Kinetic.Circle,['radius']);Kinetic.GlobalObject.addGetters(Kinetic.Circle,['radius']);Kinetic.Image=function(config){this.setDefaultAttrs({crop:{x:0,y:0,width:undefined,height:undefined}});this.shapeType="Image";config.drawFunc=function(){if(this.attrs.image!==undefined){var width=this.attrs.width!==undefined?this.attrs.width:this.attrs.image.width;var height=this.attrs.height!==undefined?this.attrs.height:this.attrs.image.height;var cropX=this.attrs.crop.x;var cropY=this.attrs.crop.y;var cropWidth=this.attrs.crop.width;var cropHeight=this.attrs.crop.height;var canvas=this.getCanvas();var context=this.getContext();context.beginPath();context.rect(0,0,width,height);context.closePath();this.fill();this.stroke();if(cropWidth!==undefined&&cropHeight!==undefined){this.drawImage(this.attrs.image,cropX,cropY,cropWidth,cropHeight,0,0,width,height);}
else{this.drawImage(this.attrs.image,0,0,width,height);}}};Kinetic.Shape.apply(this,[config]);};Kinetic.Image.prototype={setSize:function(){var size=Kinetic.GlobalObject._getSize(arguments);this.setAttrs(size);},getSize:function(){return{width:this.attrs.width,height:this.attrs.height};},setCrop:function(){this.setAttrs({crop:arguments});}};Kinetic.GlobalObject.extend(Kinetic.Image,Kinetic.Shape);Kinetic.GlobalObject.addSetters(Kinetic.Image,['height','width','image']);Kinetic.GlobalObject.addGetters(Kinetic.Image,['crop','height','width','image']);
Kinetic.Sprite=function(config){this.setDefaultAttrs({index:0,frameRate:17});config.drawFunc=function(){if(this.attrs.image!==undefined){var context=this.getContext();var anim=this.attrs.animation;var index=this.attrs.index;var f=this.attrs.animations[anim][index];context.beginPath();context.rect(0,0,f.width,f.height);context.closePath();this.drawImage(this.attrs.image,f.x,f.y,f.width,f.height,0,0,f.width,f.height);}};Kinetic.Shape.apply(this,[config]);};Kinetic.Sprite.prototype={start:function(){var that=this;var layer=this.getLayer();this.interval=setInterval(function(){that._updateIndex();layer.draw();if(that.afterFrameFunc&&that.attrs.index===that.afterFrameIndex){that.afterFrameFunc();}},1000/this.attrs.frameRate)},stop:function(){clearInterval(this.interval);},afterFrame:function(index,func){this.afterFrameIndex=index;this.afterFrameFunc=func;},_updateIndex:function(){var i=this.attrs.index;var a=this.attrs.animation;if(i<this.attrs.animations[a].length-1){this.attrs.index++;}
else{this.attrs.index=0;}}};Kinetic.GlobalObject.extend(Kinetic.Sprite,Kinetic.Shape);Kinetic.GlobalObject.addSetters(Kinetic.Sprite,['animation','animations','index']);Kinetic.GlobalObject.addGetters(Kinetic.Sprite,['animation','animations','index']);/**/
Kinetic.Polygon=function(config){this.setDefaultAttrs({points:[]});this.shapeType="Polygon";config.drawFunc=function(){var context=this.getContext();context.beginPath();context.moveTo(this.attrs.points[0].x,this.attrs.points[0].y);for(var n=1;n<this.attrs.points.length;n++){context.lineTo(this.attrs.points[n].x,this.attrs.points[n].y);}
context.closePath();this.fill();this.stroke();};Kinetic.Shape.apply(this,[config]);};Kinetic.GlobalObject.extend(Kinetic.Polygon,Kinetic.Shape);Kinetic.GlobalObject.addSetters(Kinetic.Polygon,['points']);Kinetic.GlobalObject.addGetters(Kinetic.Polygon,['points']);Kinetic.RegularPolygon=function(config){this.setDefaultAttrs({radius:0,sides:0});this.shapeType="RegularPolygon";config.drawFunc=function(){ var context=this.getContext();context.beginPath();context.moveTo(0,0-this.attrs.radius);for(var n=1;n<this.attrs.sides;n++){var x=this.attrs.radius*Math.sin(n*2*Math.PI/this.attrs.sides);var y=-1*this.attrs.radius*Math.cos(n*2*Math.PI/this.attrs.sides);context.lineTo(x,y);}
context.closePath();this.fill();this.stroke();};Kinetic.Shape.apply(this,[config]);};Kinetic.GlobalObject.extend(Kinetic.RegularPolygon,Kinetic.Shape);Kinetic.GlobalObject.addSetters(Kinetic.Rect,['radius','sides']);Kinetic.GlobalObject.addGetters(Kinetic.Rect,['radius','sides']);Kinetic.Star=function(config){this.setDefaultAttrs({numPoints:0,innerRadius:0,outerRadius:0});this.shapeType="Star";config.drawFunc=function(){var context=this.getContext();context.beginPath();context.moveTo(0,0-this.attrs.outerRadius);for(var n=1;n<this.attrs.numPoints*2;n++){var radius=n%2===0?this.attrs.outerRadius:this.attrs.innerRadius;var x=radius*Math.sin(n*Math.PI/this.attrs.numPoints);var y=-1*radius*Math.cos(n*Math.PI/this.attrs.numPoints);context.lineTo(x,y);}
context.closePath();this.fill();this.stroke();};Kinetic.Shape.apply(this,[config]);};Kinetic.GlobalObject.extend(Kinetic.Star,Kinetic.Shape);Kinetic.GlobalObject.addSetters(Kinetic.Star,['numPoints','innerRadius','outerRadius']);Kinetic.GlobalObject.addGetters(Kinetic.Star,['numPoints','innerRadius','outerRadius']);/**/
Kinetic.Text=function(config){this.setDefaultAttrs({fontFamily:'Calibri',text:'',fontSize:12,align:'left',verticalAlign:'top',padding:0,fontStyle:'normal',width:'auto',detectionType:'pixel'});this.shapeType="Text";config.drawFunc=function(){var context=this.getContext();context.font=this.attrs.fontStyle+' '+this.attrs.fontSize+'pt '+this.attrs.fontFamily;context.textBaseline='middle';var textHeight=this.getTextHeight();var textWidth=this.attrs.width==='auto'?this.getTextWidth():this.attrs.width;var p=this.attrs.padding;var x=0;var y=0;var that=this;switch(this.attrs.align){case 'center':x=textWidth/-2-p;break;case 'right':x=-1*textWidth-p;break;}
switch(this.attrs.verticalAlign){case 'middle':y=textHeight/-2-p;break;case 'bottom':y=-1*textHeight-p;break;}
context.save();context.beginPath();context.rect(x,y,textWidth+p*2,textHeight+p*2);context.closePath();this.fill();this.stroke();context.restore();var tx=p+x;var ty=textHeight/2+p+y;context.save();if(this.attrs.width!=='auto'){context.beginPath();context.rect(x,y,textWidth+p,textHeight+p*2);context.closePath();context.clip();}
this.fillText(this.attrs.text,tx,ty);this.strokeText(this.attrs.text,tx,ty);context.restore();};Kinetic.Shape.apply(this,[config]);};Kinetic.Text.prototype={getTextWidth:function(){return this.getTextSize().width;},getTextHeight:function(){return this.getTextSize().height;},getTextSize:function(){var context=this.getContext();if(!context){var dummyCanvas=document.createElement('canvas');context=dummyCanvas.getContext('2d');}
context.save();context.font=this.attrs.fontStyle+' '+this.attrs.fontSize+'pt '+this.attrs.fontFamily;var metrics=context.measureText(this.attrs.text);context.restore();return{width:metrics.width,height:parseInt(this.attrs.fontSize,10)};}};Kinetic.GlobalObject.extend(Kinetic.Text,Kinetic.Shape);Kinetic.GlobalObject.addSetters(Kinetic.Text,['fontFamily','fontSize','fontStyle','textFill','textStroke','textStrokeWidth','padding','align','verticalAlign','text','width']);Kinetic.GlobalObject.addGetters(Kinetic.Text,['fontFamily','fontSize','fontStyle','textFill','textStroke','textStrokeWidth','padding','align','verticalAlign','text','width']);/**/
Kinetic.Line=function(config){this.setDefaultAttrs({points:[],lineCap:'butt',dashArray:[],detectionType:'pixel'});this.shapeType="Line";config.drawFunc=function(){var context=this.getContext();var lastPos={};context.beginPath();context.moveTo(this.attrs.points[0].x,this.attrs.points[0].y);for(var n=1;n<this.attrs.points.length;n++){var x=this.attrs.points[n].x;var y=this.attrs.points[n].y;if(this.attrs.dashArray.length>0){var lastX=this.attrs.points[n-1].x;var lastY=this.attrs.points[n-1].y;this._dashedLine(lastX,lastY,x,y,this.attrs.dashArray);}
else{context.lineTo(x,y);}}
if(!!this.attrs.lineCap){context.lineCap=this.attrs.lineCap;}
this.stroke();};Kinetic.Shape.apply(this,[config]);};Kinetic.Line.prototype={/**/
setPoints:function(points){this.setAttrs({points:points});},_dashedLine:function(x,y,x2,y2,dashArray){var context=this.getContext();var dashCount=dashArray.length;var dx=(x2-x),dy=(y2-y);var xSlope=dx>dy;var slope=(xSlope)?dy/dx:dx/dy;if(slope>9999){slope=9999;}
else if(slope<-9999){slope=-9999;}
var distRemaining=Math.sqrt(dx*dx+dy*dy);var dashIndex=0,draw=true;while(distRemaining>=0.1&&dashIndex<10000){var dashLength=dashArray[dashIndex++%dashCount];if(dashLength===0){dashLength=0.001;}
if(dashLength>distRemaining){dashLength=distRemaining;}
var step=Math.sqrt(dashLength*dashLength/(1+slope*slope));if(xSlope){x+=dx<0&&dy<0?step*-1:step;y+=dx<0&&dy<0?slope*step*-1:slope*step;}
else{x+=dx<0&&dy<0?slope*step*-1:slope*step;y+=dx<0&&dy<0?step*-1:step;}
context[draw?'lineTo':'moveTo'](x,y);distRemaining-=dashLength;draw=!draw;}
context.moveTo(x2,y2);}};Kinetic.GlobalObject.extend(Kinetic.Line,Kinetic.Shape);Kinetic.GlobalObject.addSetters(Kinetic.Line,['dashArray','lineCap']);Kinetic.GlobalObject.addGetters(Kinetic.Line,['dashArray','lineCap','points']);/**/
//
Kinetic.Path=function(config){this.shapeType="Path";this.dataArray=[];var that=this;config.drawFunc=function(){var context=this.getContext();var ca=this.dataArray;context.beginPath();for(var n=0;n<ca.length;n++){var c=ca[n].command;var p=ca[n].points;switch(c){case 'L':context.lineTo(p[0],p[1]);break;case 'M':context.moveTo(p[0],p[1]);break;case 'C':context.bezierCurveTo(p[0],p[1],p[2],p[3],p[4],p[5]);break;case 'Q':context.quadraticCurveTo(p[0],p[1],p[2],p[3]);break;case 'A':var cx=p[0],cy=p[1],rx=p[2],ry=p[3],theta=p[4],dTheta=p[5],psi=p[6],fs=p[7];var r=(rx>ry)?rx:ry;var scaleX=(rx>ry)?1:rx/ry;var scaleY=(rx>ry)?ry/rx:1;context.translate(cx,cy);context.rotate(psi);context.scale(scaleX,scaleY);context.arc(0,0,r,theta,theta+dTheta,1-fs);context.scale(1/scaleX,1/scaleY);context.rotate(-psi);context.translate(-cx,-cy);break;case 'z':context.closePath();break;}}
this.fill();this.stroke();};Kinetic.Shape.apply(this,[config]);this.dataArray=this.getDataArray();this.on('dataArrayChange',function(){that.dataArray=that.getDataArray();});};Kinetic.Path.prototype={getDataArray:function(){var cs=this.attrs.data;var cc=['m','M','l','L','v','V','h','H','z','Z','c','C','q','Q','t','T','s','S','a','A'];cs=cs.replace(new RegExp(' ','g'),',');for(var n=0;n<cc.length;n++){cs=cs.replace(new RegExp(cc[n],'g'),'|'+cc[n]);}
var arr=cs.split('|');var ca=[];var cpx=0;var cpy=0;for(var n=1;n<arr.length;n++){var str=arr[n];var c=str.charAt(0);str=str.slice(1);str=str.replace(new RegExp(',-','g'),'-');str=str.replace(new RegExp('-','g'),',-');var p=str.split(',');if(p.length>0&&p[0]===''){p.shift();}
for(var i=0;i<p.length;i++){p[i]=parseFloat(p[i]);}
while(p.length>0){if(isNaN(p[0]))
break;var cmd=undefined;var points=[];switch(c){case 'l':cpx+=p.shift();cpy+=p.shift();cmd='L';points.push(cpx,cpy);break;case 'L':cpx=p.shift();cpy=p.shift();points.push(cpx,cpy);break;case 'm':cpx+=p.shift();cpy+=p.shift();cmd='M';points.push(cpx,cpy);c='l';break;case 'M':cpx=p.shift();cpy=p.shift();cmd='M';points.push(cpx,cpy);c='L';break;case 'h':cpx+=p.shift();cmd='L';points.push(cpx,cpy);break;case 'H':cpx=p.shift();cmd='L';points.push(cpx,cpy);break;case 'v':cpy+=p.shift(); cmd='L';points.push(cpx,cpy);break;case 'V':cpy=p.shift();cmd='L';points.push(cpx,cpy);break;case 'C':points.push(p.shift(),p.shift(),p.shift(),p.shift());cpx=p.shift();cpy=p.shift();points.push(cpx,cpy);break;case 'c':points.push(cpx+p.shift(),cpy+p.shift(),cpx+p.shift(),cpy+p.shift());cpx+=p.shift();cpy+=p.shift();cmd='C'
points.push(cpx,cpy);break;case 'S':var ctlPtx=cpx,ctlPty=cpy;var prevCmd=ca[ca.length-1];if(prevCmd.command==='C'){ctlPtx=cpx+(cpx-prevCmd.points[2]);ctlPty=cpy+(cpy-prevCmd.points[3]);}
points.push(ctlPtx,ctlPty,p.shift(),p.shift())
cpx=p.shift();cpy=p.shift();cmd='C';points.push(cpx,cpy);break;case 's':var ctlPtx=cpx,ctlPty=cpy;var prevCmd=ca[ca.length-1];if(prevCmd.command==='C'){ctlPtx=cpx+(cpx-prevCmd.points[2]);ctlPty=cpy+(cpy-prevCmd.points[3]);}
points.push(ctlPtx,ctlPty,cpx+p.shift(),cpy+p.shift())
cpx+=p.shift();cpy+=p.shift();cmd='C';points.push(cpx,cpy);break;case 'Q':points.push(p.shift(),p.shift());cpx=p.shift();cpy=p.shift();points.push(cpx,cpy);break;case 'q':points.push(cpx+p.shift(),cpy+p.shift());cpx+=p.shift();cpy+=p.shift();cmd='Q'
points.push(cpx,cpy);break;case 'T': var ctlPtx=cpx,ctlPty=cpy;var prevCmd=ca[ca.length-1];if(prevCmd.command==='Q'){ctlPtx=cpx+(cpx-prevCmd.points[0]);ctlPty=cpy+(cpy-prevCmd.points[1]);}
cpx=p.shift();cpy=p.shift();cmd='Q';points.push(ctlPtx,ctlPty,cpx,cpy);break;case 't':var ctlPtx=cpx,ctlPty=cpy;var prevCmd=ca[ca.length-1];if(prevCmd.command==='Q'){ctlPtx=cpx+(cpx-prevCmd.points[0]);ctlPty=cpy+(cpy-prevCmd.points[1]);}
cpx+=p.shift();cpy+=p.shift();cmd='Q';points.push(ctlPtx,ctlPty,cpx,cpy);break;case 'A':var rx=p.shift(),ry=p.shift(),psi=p.shift(),fa=p.shift(),fs=p.shift();var x1=cpx,y1=cpy;cpx=p.shift(),cpy=p.shift();cmd='A';points=this._convertEndpointToCenterParameterization(x1,y1,cpx,cpy,fa,fs,rx,ry,psi);break;case 'a':var rx=p.shift(),ry=p.shift(),psi=p.shift(),fa=p.shift(),fs=p.shift();var x1=cpx,y1=cpy;cpx+=p.shift(),cpy+=p.shift();cmd='A';points=this._convertEndpointToCenterParameterization(x1,y1,cpx,cpy,fa,fs,rx,ry,psi);break;}
ca.push({command:cmd|| c,points:points});}
if(c==='z'||c==='Z')
ca.push({command:'z',points:[]});}
return ca;},_convertEndpointToCenterParameterization:function(x1,y1,x2,y2,fa,fs,rx,ry,psiDeg){var psi=psiDeg*(Math.PI/180.0);var xp=Math.cos(psi)*(x1-x2)/2.0+Math.sin(psi)*(y1-y2)/2.0;var yp=-1*Math.sin(psi)*(x1-x2)/2.0+Math.cos(psi)*(y1-y2)/2.0;var lambda=(xp*xp)/(rx*rx)+(yp*yp)/(ry*ry);if(lambda>1){rx*=Math.sqrt(lambda);ry*=Math.sqrt(lambda);}
var f=Math.sqrt((((rx*rx)*(ry*ry))-((rx*rx)*(yp*yp))-((ry*ry)*(xp*xp)))/((rx*rx)*(yp*yp)+(ry*ry)*(xp*xp)));if(fa==fs)
f*=-1;if(isNaN(f))
f=0;var cxp=f*rx*yp/ry;var cyp=f*-ry*xp/rx;var cx=(x1+x2)/2.0+Math.cos(psi)*cxp-Math.sin(psi)*cyp;var cy=(y1+y2)/2.0+Math.sin(psi)*cxp+Math.cos(psi)*cyp;var vMag=function(v){return Math.sqrt(v[0]*v[0]+v[1]*v[1]);}
var vRatio=function(u,v){return(u[0]*v[0]+u[1]*v[1])/(vMag(u)*vMag(v))}
var vAngle=function(u,v){return(u[0]*v[1]<u[1]*v[0]?-1:1)*Math.acos(vRatio(u,v));}
var theta=vAngle([1,0],[(xp-cxp)/rx,(yp-cyp)/ry]);var u=[(xp-cxp)/rx,(yp-cyp)/ry];var v=[(-1*xp-cxp)/rx,(-1*yp-cyp)/ry];var dTheta=vAngle(u,v);if(vRatio(u,v)<=-1)
dTheta=Math.PI;if(vRatio(u,v)>=1)
dTheta=0;if(fs==0&&dTheta>0)
 dTheta=dTheta-2*Math.PI;if(fs==1&&dTheta<0)
dTheta=dTheta+2*Math.PI;return[cx,cy,rx,ry,theta,dTheta,psi,fs];}};Kinetic.GlobalObject.extend(Kinetic.Path,Kinetic.Shape);Kinetic.GlobalObject.addSetters(Kinetic.Path,['data']);Kinetic.GlobalObject.addGetters(Kinetic.Path,['data']);Kinetic.Transform=function(){this.m=[1,0,0,1,0,0];}
Kinetic.Transform.prototype={translate:function(x,y){this.m[4]+=this.m[0]*x+this.m[2]*y;this.m[5]+=this.m[1]*x+this.m[3]*y;},scale:function(sx,sy){this.m[0]*=sx;this.m[1]*=sx;this.m[2]*=sy;this.m[3]*=sy;},rotate:function(rad){var c=Math.cos(rad);var s=Math.sin(rad);var m11=this.m[0]*c+this.m[2]*s;var m12=this.m[1]*c+this.m[3]*s;var m21=this.m[0]*-s+this.m[2]*c; var m22=this.m[1]*-s+this.m[3]*c;this.m[0]=m11;this.m[1]=m12;this.m[2]=m21;this.m[3]=m22;},getTranslation:function(){return{x:this.m[4],y:this.m[5]};},multiply:function(matrix){var m11=this.m[0]*matrix.m[0]+this.m[2]*matrix.m[1];var m12=this.m[1]*matrix.m[0]+this.m[3]*matrix.m[1];var m21=this.m[0]*matrix.m[2]+this.m[2]*matrix.m[3];var m22=this.m[1]*matrix.m[2]+this.m[3]*matrix.m[3]; var dx=this.m[0]*matrix.m[4]+this.m[2]*matrix.m[5]+this.m[4];var dy=this.m[1]*matrix.m[4]+this.m[3]*matrix.m[5]+this.m[5];this.m[0]=m11;this.m[1]=m12;this.m[2]=m21;this.m[3]=m22;this.m[4]=dx;this.m[5]=dy;},invert:function(){var d=1/(this.m[0]*this.m[3]-this.m[1]*this.m[2]);var m0=this.m[3]*d;var m1=-this.m[1]*d;var m2=-this.m[2]*d;var m3=this.m[0]*d;var m4=d*(this.m[2]*this.m[5]-this.m[3]*this.m[4]);var m5=d*(this.m[1]*this.m[4]-this.m[0]*this.m[5]);this.m[0]=m0;this.m[1]=m1;this.m[2]=m2;this.m[3]=m3;this.m[4]=m4;this.m[5]=m5;},getMatrix:function(){return this.m;}};Kinetic.Transition=function(node,config){this.node=node;this.config=config;this.tweens=[];var that=this;function addTween(c,attrs){for(var key in c){if(key!=='duration'&&key!=='easing'&&key!=='callback'){if(Kinetic.GlobalObject._isObject(c[key])){addTween(c[key],attrs[key]);}
else{that._add(that._getTween(attrs,key,c[key]));}}}}
addTween(config,node.attrs);var finishedTweens=0;for(var n=0;n<this.tweens.length;n++){var tween=this.tweens[n];tween.onFinished=function(){finishedTweens++;if(finishedTweens>=that.tweens.length){that.onFinished();}};}};Kinetic.Transition.prototype={start:function(){for(var n=0;n<this.tweens.length;n++){this.tweens[n].start();}},stop:function(){for(var n=0;n<this.tweens.length;n++){this.tweens[n].stop();}},resume:function(){for(var n=0;n<this.tweens.length;n++){this.tweens[n].resume();}},_onEnterFrame:function(){for(var n=0;n<this.tweens.length;n++){this.tweens[n].onEnterFrame();}},_add:function(tween){this.tweens.push(tween);},_getTween:function(key,prop,val){var config=this.config;var node=this.node;var easing=config.easing;if(easing===undefined){easing='linear';}
var tween=new Kinetic.Tween(node,function(i){key[prop]=i;},Kinetic.Tweens[easing],key[prop],val,config.duration);return tween;}};Kinetic.Tween=function(obj,propFunc,func,begin,finish,duration){this._listeners=[];this.addListener(this);this.obj=obj;this.propFunc=propFunc;this.begin=begin;this._pos=begin;this.setDuration(duration);this.isPlaying=false;this._change=0;this.prevTime=0;this.prevPos=0;this.looping=false;this._time=0;this._position=0;this._startTime=0;this._finish=0;this.name='';
this.func=func;this.setFinish(finish);};Kinetic.Tween.prototype={setTime:function(t){this.prevTime=this._time;if(t>this.getDuration()){if(this.looping){this.rewind(t-this._duration);this.update();this.broadcastMessage('onLooped',{target:this,type:'onLooped'});}
else{this._time=this._duration;this.update();this.stop();this.broadcastMessage('onFinished',{target:this,type:'onFinished'});}}
else if(t<0){this.rewind();this.update();}
else{this._time=t;this.update();}},getTime:function(){return this._time;},setDuration:function(d){this._duration=(d===null||d<=0)?100000:d;},getDuration:function(){return this._duration;},setPosition:function(p){this.prevPos=this._pos;this.propFunc(p);this._pos=p;this.broadcastMessage('onChanged',{target:this,type:'onChanged'});},getPosition:function(t){if(t===undefined){t=this._time;}
return this.func(t,this.begin,this._change,this._duration);},setFinish:function(f){this._change=f-this.begin;},getFinish:function(){return this.begin+this._change;},start:function(){this.rewind();this.startEnterFrame();this.broadcastMessage('onStarted',{target:this,type:'onStarted'});},rewind:function(t){this.stop();this._time=(t===undefined)?0:t;this.fixTime();this.update();},fforward:function(){this._time=this._duration;this.fixTime();this.update();},update:function(){this.setPosition(this.getPosition(this._time));},startEnterFrame:function(){this.stopEnterFrame();this.isPlaying=true;this.onEnterFrame();},onEnterFrame:function(){if(this.isPlaying){this.nextFrame();}},nextFrame:function(){this.setTime((this.getTimer()-this._startTime)/1000);},stop:function(){this.stopEnterFrame();this.broadcastMessage('onStopped',{target:this,type:'onStopped'});},stopEnterFrame:function(){this.isPlaying=false;},continueTo:function(finish,duration){this.begin=this._pos;this.setFinish(finish);if(this._duration!==undefined){this.setDuration(duration);}
this.start();},resume:function(){this.fixTime();this.startEnterFrame();this.broadcastMessage('onResumed',{target:this,type:'onResumed'});},yoyo:function(){this.continueTo(this.begin,this._time);},addListener:function(o){this.removeListener(o);return this._listeners.push(o);},removeListener:function(o){var a=this._listeners;var i=a.length;while(i--){if(a[i]==o){a.splice(i,1);return true;}}
return false;},broadcastMessage:function(){var arr=[];for(var i=0;i<arguments.length;i++){arr.push(arguments[i]);}
var e=arr.shift();var a=this._listeners;var l=a.length;for(var i=0;i<l;i++){if(a[i][e]){a[i][e].apply(a[i],arr);}}},fixTime:function(){this._startTime=this.getTimer()-this._time*1000;},getTimer:function(){return new Date().getTime()-this._time;}};Kinetic.Tweens={'back-ease-in':function(t,b,c,d,a,p){var s=1.70158;return c*(t/=d)*t*((s+1)*t-s)+b;},'back-ease-out':function(t,b,c,d,a,p){var s=1.70158;return c*((t=t/d-1)*t*((s+1)*t+s)+1)+b;},'back-ease-in-out':function(t,b,c,d,a,p){var s=1.70158;if((t/=d/2)<1){ return c/2*(t*t*(((s*=(1.525))+1)*t-s))+b;}
return c/2*((t-=2)*t*(((s*=(1.525))+1)*t+s)+2)+b;},'elastic-ease-in':function(t,b,c,d,a,p){var s=0;if(t===0){return b;}
if((t/=d)==1){return b+c;}
if(!p){p=d*0.3;}
if(!a||a<Math.abs(c)){a=c;s=p/4;}
else{s=p/(2*Math.PI)*Math.asin(c/a);}
return-(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;},'elastic-ease-out':function(t,b,c,d,a,p){var s=0;if(t===0){return b;}
if((t/=d)==1){return b+c;}
if(!p){p=d*0.3;}
if(!a||a<Math.abs(c)){a=c;s=p/4;}
else{s=p/(2*Math.PI)*Math.asin(c/a);}
return(a*Math.pow(2,-10*t)*Math.sin((t*d-s)*(2*Math.PI)/p)+c+b);},'elastic-ease-in-out':function(t,b,c,d,a,p){var s=0;if(t===0){return b;}
if((t/=d/2)==2){return b+c;}
if(!p){p=d*(0.3*1.5);}
if(!a||a<Math.abs(c)){a=c;s=p/4;}
else{s=p/(2*Math.PI)*Math.asin(c/a);}
if(t<1){return-0.5*(a*Math.pow(2,10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p))+b;}
return a*Math.pow(2,-10*(t-=1))*Math.sin((t*d-s)*(2*Math.PI)/p)*0.5+c+b;},'bounce-ease-out':function(t,b,c,d){if((t/=d)<(1/2.75)){return c*(7.5625*t*t)+b;}
else if(t<(2/2.75)){return c*(7.5625*(t-=(1.5/2.75))*t+0.75)+b;}
else if(t<(2.5/2.75)){return c*(7.5625*(t-=(2.25/2.75))*t+0.9375)+b;}
else{return c*(7.5625*(t-=(2.625/2.75))*t+0.984375)+b;}},'bounce-ease-in':function(t,b,c,d){return c-Kinetic.Tweens['bounce-ease-out'](d-t,0,c,d)+b;},'bounce-ease-in-out':function(t,b,c,d){if(t<d/2){return Kinetic.Tweens['bounce-ease-in'](t*2,0,c,d)*0.5+b;}
else{return Kinetic.Tweens['bounce-ease-out'](t*2-d,0,c,d)*0.5+c*0.5+b;}},'ease-in':function(t,b,c,d){return c*(t/=d)*t+b;},'ease-out':function(t,b,c,d){return-c*(t/=d)*(t-2)+b;},'ease-in-out':function(t,b,c,d){if((t/=d/2)<1){return c/2*t*t+b;}
return-c/2*((--t)*(t-2)-1)+b;},'strong-ease-in':function(t,b,c,d){return c*(t/=d)*t*t*t*t+b;},'strong-ease-out':function(t,b,c,d){return c*((t=t/d-1)*t*t*t*t+1)+b;},'strong-ease-in-out':function(t,b,c,d){if((t/=d/2)<1){return c/2*t*t*t*t*t+b;}
return c/2*((t-=2)*t*t*t*t+2)+b;},'linear':function(t,b,c,d){return c*t/d+b;}};